server:
  port: 9031
spring:
  application:
    name: practise-service
  #mysql和redis数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 106.14.96.69
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #spring上传文件大小的设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  jpa: #JPA自动建表
    generate-ddl: true
    hibernate:
      ddl-auto: update
    #    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

#mybatis-plus的配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.panxc.practise.entity
  configuration:
    map-underscore-to-camel-case: true
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: D:/log/goods-service.log